"""add_concepts_table

Revision ID: 1611c43dcb7f
Revises: merge001heads01
Create Date: 2026-05-03 17:09:50.800756

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "1611c43dcb7f"
down_revision: str | Sequence[str] | None = "merge001heads01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concepts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("related_papers", sa.Text(), nullable=False),
        sa.Column("related_concepts", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_concepts_project_id"), "concepts", ["project_id"], unique=False)
    op.alter_column(
        "audio_overviews",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.drop_constraint(None, "collection_papers", type_="foreignkey")
    op.drop_constraint(None, "collection_papers", type_="foreignkey")
    op.create_foreign_key(None, "collection_papers", "papers", ["paper_id"], ["id"])
    op.create_foreign_key(None, "collection_papers", "collections", ["collection_id"], ["id"])
    op.drop_constraint(None, "collections", type_="foreignkey")
    op.create_foreign_key(None, "collections", "projects", ["project_id"], ["id"])
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "paper_versions", "abstract", existing_type=sa.TEXT(), nullable=False, existing_server_default=sa.text("('')")
    )
    op.alter_column(
        "paper_versions",
        "journal",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_server_default=sa.text("('')"),
    )
    op.alter_column(
        "paper_versions",
        "citation_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "paper_versions",
        "is_preprint",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("'1'"),
    )
    op.alter_column(
        "paper_versions",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.drop_constraint(None, "paper_versions", type_="foreignkey")
    op.create_foreign_key(None, "paper_versions", "papers", ["paper_id"], ["id"])
    op.alter_column(
        "reading_sessions",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.drop_constraint(None, "review_extractions", type_="foreignkey")
    op.drop_constraint(None, "review_extractions", type_="foreignkey")
    op.create_foreign_key(None, "review_extractions", "papers", ["paper_id"], ["id"])
    op.create_foreign_key(None, "review_extractions", "reviews", ["review_id"], ["id"])
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.create_foreign_key(None, "reviews", "projects", ["project_id"], ["id"])
    op.alter_column("subscriptions", "sources", existing_type=sqlite.JSON(), nullable=False)
    op.drop_index(op.f("ix_team_members_invite_code"), table_name="team_members")
    op.create_unique_constraint(None, "team_members", ["invite_code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team_members", type_="unique")
    op.create_index(op.f("ix_team_members_invite_code"), "team_members", ["invite_code"], unique=1)
    op.alter_column("subscriptions", "sources", existing_type=sqlite.JSON(), nullable=True)
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.create_foreign_key(None, "reviews", "projects", ["project_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(None, "review_extractions", type_="foreignkey")
    op.drop_constraint(None, "review_extractions", type_="foreignkey")
    op.create_foreign_key(None, "review_extractions", "reviews", ["review_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "review_extractions", "papers", ["paper_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "reading_sessions",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.drop_constraint(None, "paper_versions", type_="foreignkey")
    op.create_foreign_key(None, "paper_versions", "papers", ["paper_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "paper_versions",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "paper_versions",
        "is_preprint",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("'1'"),
    )
    op.alter_column(
        "paper_versions",
        "citation_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "paper_versions",
        "journal",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_server_default=sa.text("('')"),
    )
    op.alter_column(
        "paper_versions", "abstract", existing_type=sa.TEXT(), nullable=True, existing_server_default=sa.text("('')")
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.drop_constraint(None, "collections", type_="foreignkey")
    op.create_foreign_key(None, "collections", "projects", ["project_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(None, "collection_papers", type_="foreignkey")
    op.drop_constraint(None, "collection_papers", type_="foreignkey")
    op.create_foreign_key(None, "collection_papers", "collections", ["collection_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "collection_papers", "papers", ["paper_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "audio_overviews",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.drop_index(op.f("ix_concepts_project_id"), table_name="concepts")
    op.drop_table("concepts")
    # ### end Alembic commands ###
