"""add project icon and color

Revision ID: d409bcf884d8
Revises: 72c0845957f5
Create Date: 2026-03-11 16:54:06.254348

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d409bcf884d8"
down_revision: str | Sequence[str] | None = "72c0845957f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("icon", sa.String(length=50), nullable=False))
    op.add_column("projects", sa.Column("color", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "color")
    op.drop_column("projects", "icon")
    # ### end Alembic commands ###
