"""add has_formula and figure_path to paper_chunks

Revision ID: f2bee250c39f
Revises: e8f2a3b1c4d5
Create Date: 2026-03-15 17:30:22.425479

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2bee250c39f"
down_revision: str | Sequence[str] | None = "e8f2a3b1c4d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("paper_chunks", sa.Column("has_formula", sa.Boolean(), server_default=sa.text("0"), nullable=False))
    op.add_column(
        "paper_chunks", sa.Column("figure_path", sa.String(length=500), server_default=sa.text("''"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paper_chunks", "figure_path")
    op.drop_column("paper_chunks", "has_formula")
    # ### end Alembic commands ###
